"""Local, simulation-only foundations for the trad project."""

__version__ = "0.1.0"

from .config import (
    ConfigurationError,
    Instrument,
    MarketDataSource,
    PerpetualFuturesConfig,
    ResourceConfig,
    RunConfig,
    RunMode,
    SafetyConfig,
    SpotConfig,
    load_config,
)
from .binance_spot import (
    BinanceSpotAPIError,
    BinanceSpotConnectorError,
    BinanceSpotConnectorSettings,
    BinanceSpotDataError,
    BinanceSpotHTTPError,
    BinanceSpotPublicConnector,
    BinanceSpotRequestError,
    BinanceSpotResponseError,
    BinanceSpotTransportError,
)
from .market_data import (
    BidAsk,
    DataHealth,
    DataHealthStatus,
    DataSafetyError,
    DataValidationError,
    DeterministicReplay,
    MarketData,
    MarketDataKind,
    MarketDataPolicy,
    MarketDataSafetyMonitor,
    OHLCV,
    OrderBook,
    OrderBookLevel,
    Ticker,
    Trade,
    TradeSide,
    event_kind,
)

__all__ = [
    "ConfigurationError",
    "BinanceSpotAPIError",
    "BinanceSpotConnectorError",
    "BinanceSpotConnectorSettings",
    "BinanceSpotDataError",
    "BinanceSpotHTTPError",
    "BinanceSpotPublicConnector",
    "BinanceSpotRequestError",
    "BinanceSpotResponseError",
    "BinanceSpotTransportError",
    "Instrument",
    "MarketDataSource",
    "PerpetualFuturesConfig",
    "ResourceConfig",
    "RunConfig",
    "RunMode",
    "SafetyConfig",
    "SpotConfig",
    "load_config",
    "BidAsk",
    "DataHealth",
    "DataHealthStatus",
    "DataSafetyError",
    "DataValidationError",
    "DeterministicReplay",
    "MarketData",
    "MarketDataKind",
    "MarketDataPolicy",
    "MarketDataSafetyMonitor",
    "OHLCV",
    "OrderBook",
    "OrderBookLevel",
    "Ticker",
    "Trade",
    "TradeSide",
    "event_kind",
]
